version: "3.7"

services:
  solr_server:
    container_name: solr_server
    user: solr
    build:
      context: ./solr
      dockerfile: dockerfile
    volumes:
      - "./solr/data:/opt/solr/data"
      - "./solr/setup.sh:/opt/solr/setup.sh"
    ports:
      - 8983:8983
